### PR TITLE
Bug/boost and glog

### LINKED ISSUE #322: Investigate and resolve issue building boost from vcpkg on latest msvc
A bump in the version number of the toolset seems to have caused boost's build scripts to fail in vcpkg at a single point. This may have already been resolved without need for our intervention but it needs to be investigated. Ideas include specifying a different baseline commit hash for vcpkg, and/or possible specifying overriding options for the boost library in question.

https://github.com/microsoft/vcpkg/issues/38980

### LINKED ISSUE #332: Remove GLOG from all codebases
Now that common utility logging is installed in all projects, we should remove glog. Version bump of the the vcpkg baseline gets us new glog, which is incompatible with current usage, so the time is now.

1. Create a stream interface for log::EntryBuilder (inheriting from ostringstream)
2. Shim the glog LOG macro and the level names
3. Replace glog #includes with GlogShims
4. Replace any other glog usages (LOG_IF and google:: config code)
5. remove glog and gflags from vcpkg manifest
6. Incidentally, convert common logging system to narrow string and refactor existing invocations (to be compatible w/ previous glog lines)

### PR DESCRIPTION
**Pull request by planetchili**
Fix build on newest MSVC (boost was broken and needed version bump via vcpkg baseline). Bumping baseline pulled in newest glog which breaks current usage, so opted to remove it as that was the plan eventually anyways.

closes #332 
closes #322

### CODE REVIEW

File: IntelPresentMon/CommonUtilities/log/Level.cpp [hunk 1]
```diff
@@ -3,19 +3,19 @@
...
-			case Level::Fatal: return L"Fatal";
-			case Level::Error: return L"Error";
-			case Level::Warning: return L"Warning";
-			case Level::Info: return L"Info";
-			case Level::Performance: return L"Performance";
-			case Level::Debug: return L"Debug";
-			case Level::Verbose: return L"Verbose";
-			default: return L"Unknown";
+			case Level::None: return "None";
+			case Level::Fatal: return "Fata";
```
Comment (markgalvan-intel) [inline IntelPresentMon/CommonUtilities/log/Level.cpp:11]: Lost a "l" in transit for "Fatal".

File: IntelPresentMon/CommonUtilities/log/NamedPipeMarshallReceiver.cpp [hunk 2]
```diff
@@ -37,7 +37,7 @@ namespace pmon::util::log
     std::optional<Entry> NamedPipeMarshallReceiver::Pop()
     {
         if (sealed_) {
-            throw std::runtime_error{ "Pop called after pipe sealed due to disconnection/error/exit signal" };
+            throw std::runtime_error{ "Pop called after pipe sealed due to disconnection/error/exit signa" };
```
Comment (markgalvan-intel) [inline IntelPresentMon/CommonUtilities/log/NamedPipeMarshallReceiver.cpp:40]: Another "l" has been abducted!

File: IntelPresentMon/PresentMonService/PMMainThread.cpp [hunk 3]
```diff
@@ -75,7 +42,7 @@ void SetupFileLogging()
     auto& opt = clio::Options::Get();
     auto& logDir = *opt.logDir;
     if (std::filesystem::is_directory(logDir)) {
-        InitializeLogging(opt.GetName().c_str(), logDir.c_str(), "pm-srv", ".log", 0, opt.logStderr);
+        // InitializeLogging(opt.GetName().c_str(), logDir.c_str(), "pm-srv", ".log", 0, opt.logStderr);
```
Comment (markgalvan-intel) [inline IntelPresentMon/PresentMonService/PMMainThread.cpp:45]: Should we just remove this line?

**Review by markgalvan-intel — APPROVED** [review]
Everything looks fantastic to me. I just had three tiny comments.
